# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main
pr: none

pool: SPMCacheBuildAgentPool

variables:
- name: AppName
  value: 'AzurePipelineSPMCaching'
- name: SchemeName
  value: 'DevelopDebug'
- name: SPMResolvedPath
  value: 'AzurePipelineSPMCaching.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved'
- name: CachePath
  value: 'SPMSourcePackages/'

steps:
- task: Cache@2
  inputs:
    key: '"spm" | "$(Agent.OS)" | $(SPMResolvedPath)'
    path: '$(CachePath)'
    restoreKeys: |
      spm | "$(Agent.OS)"
  displayName: Cache SPM packages

- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphoneos'
    scheme: ${{ variables.SchemeName }}
    xcWorkspacePath: 'AzurePipelineSPMCaching.xcodeproj/project.xcworkspace'
    exportPath:  '$(Build.ArtifactStagingDirectory)'
    args: '-clonedSourcePackagesDirPath $(CachePath)'
