# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main
pr: none

pool: SPMCacheBuildAgentPool

variables:
- name: AppName
  value: 'AzurePipelineSPMCaching'
- name: SchemeName
  value: 'DevelopDebug'
- name: SPMResolvedPath
  value: 'AzurePipelineSPMCaching.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved'
- name: ConfigurationName
  value: 'Debug'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphoneos'
    scheme: ${{ variables.SchemeName }}
    configuration: ${{ variables.ConfigurationName }}
    xcWorkspacePath: 'AzurePipelineSPMCaching.xcodeproj/project.xcworkspace'
    exportPath:  '$(Build.ArtifactStagingDirectory)'
